#!/usr/bin/env bash
#
# Bundle harness.sh + templates/ into a single self-contained release script.
# Output: dist/harness.sh (curl-installable), dist/install.sh
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/harness.sh"
OUT="$ROOT/dist"
TEMPLATES="$ROOT/templates"

[ -f "$SRC" ] || { echo "error: harness.sh not found" >&2; exit 1; }
[ -d "$TEMPLATES" ] || { echo "error: templates/ not found" >&2; exit 1; }
command -v python3 >/dev/null 2>&1 || { echo "error: python3 required to bundle" >&2; exit 1; }

mkdir -p "$OUT"
TAR="$(mktemp)"
trap 'rm -f "$TAR"' EXIT

tar -czf "$TAR" -C "$TEMPLATES" .

python3 - "$SRC" "$TAR" "$OUT/harness.sh" <<'PY'
import base64, sys, pathlib

src_path, tar_path, out_path = sys.argv[1:4]
src = pathlib.Path(src_path).read_text()
if "# __HARNESS_BUNDLE_START__" in src:
    src = src.split("# __HARNESS_BUNDLE_START__", 1)[0].rstrip() + "\n"

b64 = base64.b64encode(pathlib.Path(tar_path).read_bytes()).decode()
inject = (
    "\n# __HARNESS_BUNDLE_START__\n"
    "# Generated by scripts/bundle.sh — do not edit.\n"
    "HARNESS_BUNDLED=1\n"
    f"HARNESS_TAR_B64={b64!r}\n"
    "# __HARNESS_BUNDLE_END__\n"
)
needle = "set -euo pipefail\n"
if needle not in src:
    sys.exit("error: could not find set -euo pipefail in harness.sh")
out = src.replace(needle, needle + inject, 1)
pathlib.Path(out_path).write_text(out)
PY

chmod +x "$OUT/harness.sh"
cp "$ROOT/install.sh" "$OUT/install.sh"
chmod +x "$OUT/install.sh"

BYTES="$(wc -c < "$OUT/harness.sh" | tr -d ' ')"
VER="$("$OUT/harness.sh" version 2>/dev/null || true)"
echo "Bundled $VER -> $OUT/harness.sh ($BYTES bytes)"
echo "Copied install.sh -> $OUT/install.sh"
